name: Site Monitor (Hourly) 🌐

on:
  schedule:
    # CRON-выражение: 0 * * * *
    # Запускает скрипт каждые 2 часа
    - cron: '0 */2 * * *'
  # Позволяет запускать скрипт вручную через интерфейс GitHub Actions
  workflow_dispatch: 

jobs:
  check-sites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ⬇️
        uses: actions/checkout@v4
      
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 
      
      - name: Install dependencies 🛠️
        # Устанавливаем необходимую библиотеку requests
        run: | 
             pip install cloudscraper
             pip install curl_cffi
        
      - name: Run site check script ▶️
        run: python monitoring_bot.py
        env:
          # Передаем секреты (токен и ID чата) из настроек репозитория в скрипт
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
